name: Build Configurator
on:
  push:
  pull_request:
  workflow_call:

jobs:
    build-mac-arm64:
        runs-on: macos-15
        steps:
        - uses: actions/checkout@v4
        - name: Setup environment
          env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          run: |
            COMMIT_ID=${{ github.event.pull_request.head.sha }}
            COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
            BUILD_SUFFIX=ci-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
            VERSION=$(grep version package.json | sed 's/.*"\([0-9][0-9]*.[0-9]*.[0-9]*\)".*/\1/g')
            echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
            echo "BUILD_NAMEarm64=inav-configurator_MacOS_arm64_${VERSION}_${BUILD_SUFFIX}" >> $GITHUB_ENV
        - uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Install Setuptools
          run: python3 -m pip install --break-system-packages setuptools
        - name: Install deps
          uses: nick-fields/retry@v3
          with:
            max_attempts: 3
            retry_on: error
            command: yarn install --foreground-scripts
            timeout_minutes: 10
            on_retry_command: rm -rfv node_modules
        - name: Build MacOS arm64
          run: yarn run make -- --arch="arm64"
        - name: Upload MacOS arm64 zip
          uses: actions/upload-artifact@v4
          with:
            name: ${{env.BUILD_NAMEarm64}}_ZIP
            path: ./out/make/zip/darwin/arm64/*.zip
        - name: Upload MacOS arm64 dmg
          uses: actions/upload-artifact@v4
          with:
            name: ${{env.BUILD_NAMEarm64}}_DMG
            path: ./out/make/*arm64*.dmg
